name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 11
    - name: Build with Maven
      run: mvn -B test-compile
    - name: Run tests
      timeout-minutes: 10
      run: mvn -B test
